import { Colophon, Mast, Subscriptions } from "@/components/bureau";
import {
  HRule,
  Mark,
  Pill,
  SCaps,
  SectionMast,
} from "@/components/bureau/primitives";
import {
  CALENDLY,
  GROT,
  INK,
  INK15,
  INK35,
  INK55,
  INK70,
  PAPER,
  PAPER2,
  SERIF,
  YEL,
} from "@/lib/tokens";

const CHAPTERS: ReadonlyArray<{
  n: string;
  title: string;
  body: string;
  takeaway: string;
}> = [
  {
    n: "01",
    title: "Research Before You Write",
    body: "The biggest mistake in content writing is beginning with a blank document. Spend three times as long on research as on writing. Start with the search results for your target keyword: what do the top-ranking pages say? What questions do they fail to answer? What would make someone read your version instead of theirs? Then go deeper: academic papers, industry reports, original data, expert interviews. Your goal is to be the most informed writer on this topic on the day you write. The quality of your research determines the ceiling of your content quality.",
    takeaway: "Research longer. Write faster. A well-researched piece practically writes itself.",
  },
  {
    n: "02",
    title: "The Inverted Pyramid",
    body: "Journalism solved the reading problem a century ago: put the most important information first. Your lead paragraph should answer: who, what, where, when, why — or at least the most critical three. Everything after the lead is supporting detail, background, and elaboration. Online readers scan before they commit. If your most important point is buried in paragraph seven, most readers will never reach it. Write your conclusion first, then fill in the reasoning. This inverts the academic writing habit that most of us were trained in — and it makes every piece more readable.",
    takeaway: "Lead with the conclusion. The reader decides whether to invest in your piece in the first three sentences.",
  },
  {
    n: "03",
    title: "The Headline Is Half the Article",
    body: "David Ogilvy: 'When you have written your headline, you have spent eighty cents out of your dollar.' A headline has one job: get the next sentence read. Headline formulas that consistently work: the specific number ('7 Things That...'), the challenge to a belief ('Why X Is Wrong About Y'), the how-to with a specific outcome ('How to Get Covered in Forbes Without a PR Agency'), and the counter-intuitive claim ('The Less You Post, the More People Read'). Test every headline against this question: if this appeared in my inbox, would I open it?",
    takeaway: "Write 10 headlines before you write the first paragraph. The first five are obvious. The next five are interesting.",
  },
  {
    n: "04",
    title: "Active Voice, Always",
    body: "Passive voice hides agency and creates cognitive load. 'The report was written by the team' makes the reader do extra work to understand who did what. 'The team wrote the report' is clear. Passive voice often appears when writers are uncertain about their claims, or when institutions want to avoid accountability. In marketing copy, passive voice weakens your value proposition: 'Results are generated by our process' versus 'Our process generates results.' Same words, different impact. Run the 'by zombies' test on every sentence: if you can add 'by zombies' after the verb and it makes sense, it's passive.",
    takeaway: "If you can add 'by zombies' and the sentence makes sense, it's passive. Rewrite it.",
  },
  {
    n: "05",
    title: "Sentence Length and Rhythm",
    body: "Short sentences create urgency. They land. They stop the reader. Long sentences, by contrast, allow the writer to build momentum, to accumulate detail, and to carry the reader through a more complex idea before releasing them at a full stop. The best writing alternates between both. The rhythm of varied sentence lengths is what makes prose feel alive rather than monotonous. Read your work aloud: if you run out of breath, the sentence is too long. If every sentence sounds the same, you have a rhythm problem. Vary length deliberately, not accidentally.",
    takeaway: "Vary sentence length deliberately. Short for emphasis. Long for complexity. Alternate.",
  },
  {
    n: "06",
    title: "The Specific Detail",
    body: "Vague writing is forgettable. Specific writing is memorable. 'We helped a mid-market company grow their revenue' tells the reader nothing they can evaluate. 'We helped a 23-person logistics software company in Phoenix grow their ARR from $1.2M to $2.1M in 14 months' tells them who you work with, what you do, and what to expect. Specificity does three things: it increases credibility (because liars are vague), it makes the claim verifiable (which builds trust), and it makes the reader's imagination activate (which creates engagement). Always choose the concrete detail over the abstract claim.",
    takeaway: "Replace every abstract claim with a specific detail. Specificity is the foundation of credibility.",
  },
  {
    n: "07",
    title: "The Edit: How to Cut Without Killing",
    body: "Good writing is rewriting. The first draft is for getting ideas out; the second draft is for making them clear; the third draft is for making them sharp. When editing, read the piece aloud — the ear catches what the eye misses. Look for: adverbs (usually deletable), filler phrases ('it is worth noting that', 'in order to', 'the fact that'), the passive voice, hedging language ('kind of', 'sort of', 'in some ways'), and redundancy (saying the same thing twice in adjacent sentences). Cut until it hurts, then cut a little more. Hemingway: 'The first draft of anything is shit.'",
    takeaway: "Cut every adverb. Cut every filler phrase. Cut every hedge. If cutting a sentence doesn't change the meaning, cut it.",
  },
  {
    n: "08",
    title: "Transitions That Hold",
    body: "Transitions are the connective tissue of long-form writing. They tell the reader: here is where we were, here is where we are going, here is why we are going there. The weakest transitions are conjunctions at the start of sentences ('And', 'But', 'So'). The strongest transitions are explicit: 'The problem with that approach is...' 'This leads to a paradox.' 'But position doesn't explain the data from 2019, when...' Every transition should earn its place. If it does not accelerate the reader toward the next idea, cut it.",
    takeaway: "Transitions should pull the reader forward, not just link sentences. Rewrite any transition that just says 'and then'.",
  },
  {
    n: "09",
    title: "The Closing That Lands",
    body: "Most articles end with a summary of what they just said. This is the weakest possible ending — it tells the reader nothing new and gives them no reason to act. A strong closing does one of three things: zooms out (what does this mean in a larger context?), calls to action with specificity (not 'let me know your thoughts' but 'if this applies to you, book a call here'), or leaves the reader with an image or idea that stays with them. The last sentence is the one the reader carries away. Make it worth carrying.",
    takeaway: "Your last sentence is the one they remember. Never end with a summary. End with a landing.",
  },
  {
    n: "10",
    title: "Building the Writing Habit",
    body: "Writing is a practice, not a talent. The best writers are the ones who write consistently — not the ones who write perfectly when inspiration strikes. The habit stack that works: write at the same time each day (morning is best — decision fatigue is real), start with a minimum viable session (200 words, not 2,000), track streaks not word counts, and separate drafting from editing (never edit while you write). The writers who become authorities in their field are not more gifted — they are more consistent. Consistency at long time horizons is the only reliable predictor of output quality.",
    takeaway: "200 words a day, every day, beats 2,000 words when inspiration strikes. Consistency is the craft.",
  },
  {
    n: "11",
    title: "Writing for SEO Without Destroying the Prose",
    body: "The writers who hate SEO are the ones who were told to 'stuff keywords.' Modern SEO is topical authority: write the most complete, most useful, most specific piece on your topic — and the rankings follow. Practical rules: use your primary keyword in the title, first paragraph, and one subhead. Use semantically related terms naturally throughout. Write for a specific person with a specific problem, not for a search engine. Use short paragraphs and subheadings (the reader scans before they commit). Answer the question the headline promises — Google rewards completion rates. Good SEO and good writing are aligned, not opposed.",
    takeaway: "Write for one reader who has one problem. Cover the topic completely. The ranking is a consequence of that, not a target.",
  },
];

export default function WritingTipsGuidePage() {
  return (
    <div style={{ background: PAPER, fontFamily: SERIF, color: INK }}>
      <Mast active="Writing" />

      {/* ── Header ───────────────────────────────────────────── */}
      <section style={{ padding: "80px 56px 64px" }}>
        <SectionMast n="00" label="Guide IV · Writing Tips" />
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1.4fr 1fr",
            gap: 64,
            alignItems: "start",
          }}
        >
          <div>
            <Pill size={10.5} ls="0.18em">Craft &amp; Clarity</Pill>
            <h1
              style={{
                margin: "16px 0 24px",
                fontWeight: 700,
                fontSize: 80,
                lineHeight: 0.94,
                letterSpacing: "-0.03em",
              }}
            >
              Write{" "}
              <span style={{ fontStyle: "italic" }}>
                <Mark>clearly.</Mark>
              </span>
              <br />
              Write well.
            </h1>
            <p
              style={{
                margin: 0,
                fontSize: 20,
                lineHeight: 1.6,
                color: INK70,
                maxWidth: 580,
              }}
            >
              Eleven chapters on the mechanics of clear, compelling writing — from
              research and headlines to editing and the writing habit. For content
              marketers, consultants, and anyone who communicates for a living.
            </p>
          </div>

          <div style={{ paddingTop: 8 }}>
            <Pill size={10.5} ls="0.18em">In This Guide</Pill>
            <div style={{ marginTop: 16 }}>
              {CHAPTERS.map(({ n, title }) => (
                <a
                  key={n}
                  href={`#chapter-${n}`}
                  style={{
                    display: "grid",
                    gridTemplateColumns: "32px 1fr",
                    gap: 12,
                    padding: "10px 0",
                    borderBottom: `1px solid ${INK15}`,
                    textDecoration: "none",
                    color: "inherit",
                    alignItems: "baseline",
                  }}
                >
                  <SCaps size={10} ls="0.12em" color={INK35}>{n}.</SCaps>
                  <div style={{ fontFamily: SERIF, fontSize: 15, color: INK70 }}>{title}</div>
                </a>
              ))}
            </div>
          </div>
        </div>

        <div
          style={{
            display: "flex",
            gap: 32,
            marginTop: 48,
            paddingTop: 24,
            borderTop: `1px solid ${INK15}`,
          }}
        >
          {[
            { label: "Author", value: "Syed Irfan Ajmal" },
            { label: "Length", value: "11 chapters · 5,600 words" },
            { label: "Read time", value: "14 minutes" },
            { label: "Updated", value: "May 2026" },
          ].map(({ label, value }) => (
            <div key={label}>
              <SCaps size={10} ls="0.14em" color={INK35}>{label}</SCaps>
              <div style={{ marginTop: 4, fontFamily: SERIF, fontSize: 15, color: INK55 }}>{value}</div>
            </div>
          ))}
        </div>
      </section>

      <HRule />

      {/* ── Chapters ─────────────────────────────────────────── */}
      <section style={{ padding: "72px 56px" }}>
        <div style={{ maxWidth: 760 }}>
          {CHAPTERS.map(({ n, title, body, takeaway }, i) => (
            <article
              key={n}
              id={`chapter-${n}`}
              style={{
                paddingBottom: 56,
                marginBottom: 56,
                borderBottom: i < CHAPTERS.length - 1 ? `1px solid ${INK15}` : undefined,
              }}
            >
              <div style={{ display: "flex", gap: 14, alignItems: "baseline", marginBottom: 16 }}>
                <Pill size={10} ls="0.16em">Ch. {n}</Pill>
              </div>
              <h2
                style={{
                  margin: "0 0 20px",
                  fontWeight: 700,
                  fontSize: 34,
                  lineHeight: 1.1,
                  letterSpacing: "-0.02em",
                }}
              >
                {title}
              </h2>
              <p style={{ margin: "0 0 24px", fontSize: 18.5, lineHeight: 1.7, color: INK70 }}>
                {body}
              </p>
              <div
                style={{
                  background: PAPER2,
                  padding: "18px 22px",
                  borderLeft: `3px solid ${YEL}`,
                }}
              >
                <SCaps size={10} ls="0.16em" color={YEL} style={{ display: "block", marginBottom: 8 }}>
                  Key takeaway
                </SCaps>
                <div
                  style={{
                    fontFamily: SERIF,
                    fontStyle: "italic",
                    fontSize: 16.5,
                    lineHeight: 1.5,
                    color: INK,
                  }}
                >
                  {takeaway}
                </div>
              </div>
            </article>
          ))}
        </div>
      </section>

      <HRule />

      <section style={{ padding: "72px 56px", background: PAPER2 }}>
        <SectionMast n="12" label="Next Steps · Apply What You've Learned" />
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 32 }}>
          {[
            { title: "All four guides", body: "Return to the Writing hub for Personal Branding, Neuromarketing, and Storytelling.", cta: "Writing hub", href: "/writing" },
            { title: "29 long-form articles", body: "Read the full archive of long-form articles covering earned media, SEO, personal branding, and more.", cta: "All articles", href: "/blog" },
            { title: "Work with Syed", body: "Need content strategy or earned media expertise applied to your business? Start with a discovery call.", cta: "Book a call", href: CALENDLY },
          ].map(({ title, body, cta, href }) => (
            <div key={title} style={{ borderTop: `2px solid ${INK}`, paddingTop: 20 }}>
              <h3 style={{ margin: "0 0 12px", fontWeight: 700, fontSize: 22, lineHeight: 1.15 }}>{title}</h3>
              <HRule />
              <p style={{ margin: "14px 0 20px", fontSize: 16, lineHeight: 1.6, color: INK70 }}>{body}</p>
              <a
                href={href}
                target={href.startsWith("http") ? "_blank" : undefined}
                rel={href.startsWith("http") ? "noopener noreferrer" : undefined}
                style={{ fontFamily: GROT, fontWeight: 700, fontSize: 11, letterSpacing: "0.14em", textTransform: "uppercase", color: INK, textDecoration: "none" }}
              >
                {cta} →
              </a>
            </div>
          ))}
        </div>
      </section>

      <Subscriptions sectionNumber="13" />
      <Colophon />
    </div>
  );
}
