import type { Metadata } from "next";
import Script from "next/script";
import { CollabIQ } from "@/components/tools/CollabIQ";

export const metadata: Metadata = {
  title: "CollabIQ — Partnership Intelligence Tool · SIA Wire",
  description:
    "Find the right collab link building partners for your exact business. " +
    "AI-powered suggestions, qualification scorecard, personalised outreach templates, " +
    "and a full campaign brief — generated by Claude.",
};

export default function CollabIQPage() {
  return (
    <>
      {/* jsPDF for client-side PDF export — loaded after page is interactive */}
      <Script
        src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"
        strategy="lazyOnload"
      />
      <CollabIQ />
    </>
  );
}
