import type { Metadata } from "next";
import Script from "next/script";
import { Colophon, Subscriptions } from "@/components/bureau";
import { CollabIQ } from "@/components/tools/CollabIQ";
import { ScrollButtons } from "@/components/ScrollButtons";

export const metadata: Metadata = {
  title: "CollabIQ — Partnership Intelligence Tool · SIA Wire S02E06",
  description:
    "Go beyond link building. CollabIQ surfaces high-value partnership opportunities — " +
    "co-marketing allies, content collaborators, referral networks, and distribution partners — " +
    "tailored to your exact industry. AI-powered partner suggestions, qualification scorecard, " +
    "personalised outreach templates, and a full campaign brief — generated by Claude.",
};

export default function CollabIQPage() {
  return (
    <>
      {/* jsPDF for client-side PDF export */}
      <Script
        src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"
        strategy="lazyOnload"
      />
      <CollabIQ />
      <Subscriptions sectionNumber="05" />
      <Colophon />
      <ScrollButtons />
    </>
  );
}
